---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Gett started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

# The vignette uses example data from the suggested package {pharmaverseadam}.
# Only evaluate the data-dependent chunks when it is available.
has_pharmaverseadam <- requireNamespace("pharmaverseadam", quietly = TRUE)
knitr::opts_chunk$set(eval = has_pharmaverseadam)
```

# Anaysis for outputs required by PMDA in oncology

`{anaume}` is a package to generate outputs required in oncology therapeutic area by PMDA.

```{r}
library(anaume)
```

# Setup for dummy data

Dummy data are based on the `pharmaverseadam` package. Install it with
`install.packages("pharmaverseadam")` to run the examples below.

```{r}
adae <- pharmaverseadam::adae
adsl <- pharmaverseadam::adsl
```

# 

# Define types of AE to be analyzed

[To namai-san, please add MD here]

# Generate ARD
